### PR TITLE
Update to Dotty 0.14.0-RC1

### PR DESCRIPTION
**Pull request by alemannosara**

### CODE REVIEW

**Comment by alemannosara** [comment]
@nicolasstucki I could fix almost everything but there are still some problems. They are mainly due to `getListOfExpr`. I remember that you told me it would be simplified by updating dotty. How then should I pattern match?

**Comment by nicolasstucki** [comment]
Yes, it might be simpler to try to use the new pattern matching.

You should have a look at these files:
https://github.com/lampepfl/dotty/tree/master/tests/run-with-compiler/quote-matcher-string-interpolator
https://github.com/lampepfl/dotty/tree/master/tests/run-with-compiler/quote-matcher-string-interpolator-2
https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/matching/Repeated.scala
https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/matching/Literal.scala

Let me know if something does not behave as it should or if something
breaks.

Cheers,
Nicolas

**Comment by alemannosara** [comment]
> Yes, it might be simpler to try to use the new pattern matching. You should have a look at these files: https://github.com/lampepfl/dotty/tree/master/tests/run-with-compiler/quote-matcher-string-interpolator https://github.com/lampepfl/dotty/tree/master/tests/run-with-compiler/quote-matcher-string-interpolator-2 https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/matching/Repeated.scala https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/matching/Literal.scala Let me know if something does not behave as it should or if something breaks. Cheers, Nicolas
> […](#)

Thanks! It helped a lot. 

However, it seems that the pattern matching is not recognized.

**Comment by nicolasstucki** [comment]
You can cherrypick https://github.com/nicolasstucki/f-interpolators-in-Dotty-macros/commit/3d483fdd138aa609dc4769b751a391451bb434eb, it fixes the compilation issues.

**Comment by alemannosara** [comment]
> You can cherrypick [nicolasstucki@3d483fd](https://github.com/nicolasstucki/f-interpolators-in-Dotty-macros/commit/3d483fdd138aa609dc4769b751a391451bb434eb), it fixes the compilation issues.

Thank you. This indeed fixes compilation errors. 
I will still need to fix the part where we go from Expr[String] to String, which makes the tests fail.

**Pull request merged**
